## Pull the latest mySQL image
FROM mySQL:latest

## Maintainer and email
LABEL Maintainer="KwongTN <tungnan5636@gmail.com>"

## Set Timezone = Asia/Kuala_Lumpur
RUN unlink /etc/localtime
RUN ln -s /usr/share/zoneinfo/Asia/Kuala_Lumpur /etc/localtime

## Expose port 33060 for 
EXPOSE 3306 33060
